name: infinite_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  http: ^1.2.2
  stream_transform: ^2.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
